// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfentdowmqrkrltfxeqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmZW50ZG93bXFya3JsdGZ4ZXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzUxMjAsImV4cCI6MjA2NDUxMTEyMH0.J9S8ZuYMumMbTUUxhEk0IjMsGhoLwlIvo-00lSN1woE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);